apiVersion: v1
kind: Secret
metadata:
  name: repo-harbor-helm
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  name: harbor
  url: https://helm.goharbor.io