apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgres-creds
spec:
  type: kv-v1
  mount: devinfra
  path: infra/harbor/stage/postgres
  destination:
    name: postgres-creds
    create: true
    type: Opaque
    transformation:
      excludeRaw: true
      templates:
        password:
          text: '{{ .Secrets.password }}'
  refreshAfter: 30s
  vaultAuthRef: harbor-stage
