apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: s3-creds
spec:
  type: kv-v1
  mount: devinfra
  path: infra/harbor/stage/s3
  destination:
    name: s3-creds
    create: true
    type: Opaque
    transformation:
      excludeRaw: true
      templates:
        REGISTRY_STORAGE_S3_ACCESSKEY:
          text: '{{ .Secrets.registry_storage_s3_accesskey }}'
        REGISTRY_STORAGE_S3_SECRETKEY:
          text: '{{ .Secrets.registry_storage_s3_secretkey }}'
  refreshAfter: 30s
  vaultAuthRef: harbor-stage
