---
# GitLab consolidated object_store connection secret
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: gitlab-s3-connection
spec:
  type: kv-v2
  mount: devinfra
  path: infra/gitlab/stage/s3
  destination:
    name: gitlab-s3-connection
    create: true
    type: Opaque
    transformation:
      excludeRaw: true
      templates:
        connection:
          text: |
            provider: AWS
            region: {{ .Secrets.region }}
            aws_access_key_id: {{ .Secrets.access_key }}
            aws_secret_access_key: {{ .Secrets.secret_key }}
            endpoint: {{ .Secrets.endpoint }}
            path_style: true
  refreshAfter: 30s
  vaultAuthRef: gitlab-stage
---
# Registry S3 storage config secret
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: registry-s3-storage
spec:
  type: kv-v2
  mount: devinfra
  path: infra/gitlab/stage/s3
  destination:
    name: registry-s3-storage
    create: true
    type: Opaque
    transformation:
      excludeRaw: true
      templates:
        config:
          text: |
            s3:
              v4auth: true
              regionendpoint: {{ .Secrets.endpoint }}
              region: {{ .Secrets.region }}
              bucket: gitlab-registry
              accesskey: {{ .Secrets.access_key }}
              secretkey: {{ .Secrets.secret_key }}
  refreshAfter: 30s
  vaultAuthRef: gitlab-stage
